// <auto-generated />
namespace WorkersWebAPI_Tyz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitialOne : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialOne));
        
        string IMigrationMetadata.Id
        {
            get { return "201509100320515_InitialOne"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
